markdown_extensions:
  - smarty
  - toc:
      permalink: True
      separator: "_"
  - admonition
  - codehilite
  - footnotes
  - meta
site_name: 文档撰写指南
theme: material
extra_css:
  - 'stylesheets/extra.css'
plugins:
  - search
  - pdf-export